---

SITE_INSTANCES: 1
SITE_PORT: 12180
SITE_BASE_URL: "http://localhost:12180"
SSL_VERIFY: true

AUTH_REALM: 
AUTH_CLIENT: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token
